sudo apt-get install libopencv-dev -y
sudo apt-get install build-essential -y
sudo apt-get install libavformat-dev -y
sudo apt-get install x264 -y
sudo apt-get install v4l-utils -y
sudo apt-get install ffmpeg -y
sudo apt-get install libcv2.3 -y
sudo apt-get install libcvaux2.3 -y
sudo apt-get install libhighgui2.3 -y
sudo apt-get install python-opencv -y
sudo apt-get install opencv-doc -y
sudo apt-get install libcv-dev -y
sudo apt-get install libcvaux-dev -y
sudo apt-get install libhighgui-dev -y
sudo apt-get install python-numpy -y
sudo apt-get install python-scipy -y
sudo apt-get install python-matplotlib -y
sudo apt-get install python-pandas -y
sudo apt-get install python-nose -y
sudo apt-get install v4l-utils -y
sudo apt-get install libgtkglext1-dev -y
sudo apt-get install libpng12-0 -y
sudo apt-get install libpng12-dev -y
sudo apt-get install libpng++-dev -y
sudo apt-get install libpng3 -y
sudo apt-get install libpnglite-dev -y
sudo apt-get install zlib1g-dbg -y
sudo apt-get install zlib1g -y
sudo apt-get install zlib1g-dev -y
sudo apt-get install pngtools -y
sudo apt-get install libtiff4-dev -y
sudo apt-get install libtiff4 -y
sudo apt-get install libtiffxx0c2 -y
sudo apt-get install libtiff-tools -y
sudo apt-get install libjpeg8 -y
sudo apt-get install libjpeg8-dev -y
sudo apt-get install libjpeg8-dbg -y
sudo apt-get install libavcodec-dev -y
sudo apt-get install libavcodec53 -y
sudo apt-get install libavformat53 -y
sudo apt-get install libgstreamer0.10-0-dbg -y
sudo apt-get install libgstreamer0.10-0	-y
sudo apt-get install libgstreamer0.10-dev -y
sudo apt-get install libxine1-ffmpeg -y
sudo apt-get install libxine-dev -y
sudo apt-get install libxine1-bin -y
sudo apt-get install libunicap2	-y
sudo apt-get install libunicap2-dev -y
sudo apt-get install libdc1394-22-dev -y
sudo apt-get install libdc1394-22 -y
sudo apt-get install libdc1394-utils -y
sudo apt-get install libv4l-0 -y
sudo apt-get install libv4l-dev	-y
sudo apt-get install libpython2.6 -y
sudo apt-get install python-dev	-y
sudo apt-get install python2.6-dev -y
sudo apt-get install libgtk2.0-dev -y
sudo apt-get install libswscale-dev -y
sudo apt-get install libjpeg-dev -y
sudo apt-get install libwebp-dev -y
sudo apt-get install libpng-dev	-y
sudo apt-get install libtiff5-dev -y
sudo apt-get install libjasper-dev -y
sudo apt-get install libopenexr-dev -y
sudo apt-get install libgdal-dev -y
sudo apt-get install python-tk -y
sudo apt-get install python3-dev -y
sudo apt-get install python3-tk	-y
sudo apt-get install python3-numpy -y
sudo apt-get install libeigen3-dev -y